using Amazon.Runtime.Internal.Transform;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace ToolChange.Services
{
    public static class LocalizationService
    {
        private static string _currentLanguage = DeepDroid.Properties.Settings.Default.lang;

        // Dictionary<language, Dictionary<key, value>>
        private static readonly Dictionary<string, Dictionary<string, string>> _translations = new()
    {
        {
            "vi", new Dictionary<string, string>
            {
                { "Device", "Thiết bị" },
                { "Automation", "Tự động hóa" },
                { "Screen", "Xem màn hình" },
                { "langCheckBoxAutomation", "Vô hạn"},
                { "ControlClickXY", "Nhấn X, Y"},
                { "ControlSwipe", "Vuốt"},
                { "ControlRandomClick", "Click ngẫu nhiên"},
                { "ControlWait","Đợi"},
                { "TitleClickControl", "Click tọa độ"},
                { "TitleClick2Control", "Tìm text click"},
                { "ControlSearchAndClick", "Tìm đúng click"},
                { "ControlSearchWaitClick","Tìm đúng đợi" },
                { "ControlSearchAndContinue","Tìm đúng tiếp tục" },
                { "TitleClick3Control","Tìm text trong ảnh" },
                { "ControlFindAndClick", "Tìm đúng click" },
                { "ControlFindWaitClick","Tìm đúng đợi"},
                { "ControlFindAndContinue", "Tìm đúng tiếp tục" },
                { "TitleClick4Control","Xử lý logic" },
                { "TitleTextControl", "Xử lý văn bản" },
                { "ControlSendText" , "Gửi văn bản"},
                { "ControlSendTextFromFileDel", "Gửi văn bản từ file và xóa" },
                { "ControlSendTextRandomFromFile", "Gửi văn bản từ nguồn" },
                { "ControlRandomTextAndSend", "Gửi văn bản ngẫu nhiên" },
                { "ControlDelTextChar", "Xóa 1 ký tự" },
                { "ControlDelAllText", "Xóa toàn bộ" },
                { "ControlSendKey" , "Nhấn phím"},
                { "ControlCtrlA" , "Ctrl + A"},
                { "ControlCheckKeyBoard" , "Kiểm tra bàn phím"},
                { "ControlURLKEYSendText", "Danh sách key phím" },
                { "TitileDataChangeInfo" , "Xử lý hành động trên điện thoại"},
                { "ControlDataChangeInfo1", "Sao lưu" },
                { "ControlDataChangeInfo2", "Khôi phục" },
                { "ControlDataChangeInfo3", "Đăng nhập gmail" },
                { "ControlDataChangeInfo4", "Mở Chplay" },
                { "ControlDataChangeInfo5", "Thay đổi thông tin" },
                { "ControlDataChangeInfo6", "Thay đổi sim" },
                { "ControlDataChangeInfo7", "Xóa tài khoản" },
                { "ControlWaitReboot", "Chờ khởi động lại" },
                { "ControlWaitInternet", "Chờ kết nối internet" },
                { "ControlPushFile", "Gửi tệp vào phone" },
                { "ControlPullFile", "Chuyển tệp về pc" },
                { "TitleGeneral", "Gói ứng dụng" },
                { "ControlWiFiON", "Bật wifi" },
                { "ControlWiFiOFF", "Tắt wifi" },
                { "ControlOpenURL", "Mở Url" },
                { "ControlRunCommandShell", "Lệnh (shell)" },
                { "ControlOpenApp", "Mở ứng dụng" },
                { "ControlCloseApp", "Đóng ứng dụng" },
                { "ControlEnableApp", "Bật ứng dụng" },
                { "ControlDisbledApp", "Tắt ứng dụng" },
                { "ControlInstallApp", "Cài đặt ứng dụng" },
                { "ControlUninstallApp", "Gỡ cài đặt" },
                { "ControlClearDataApp", "Xóa dữ liệu" },
                { "ControlSwipeCloseApp", "Vuốt đóng app" },
                { "ControlLoadApp", "Tải ứng dụng" },
                { "ControlDeviceMenuDropBox1", "📋 Sao chép ID" },
                { "ControlDeviceMenuDropBox2", "ℹ️ Chi tiết device" },
                { "ControlDeviceMenuDropBox3", "📱 Xem màn hình" },
                { "ControlDeviceMenuDropBox4", "🌐 Fake proxy HTTP" },
                { "ControlDeviceMenuDropBox4_1", "🌐 Fake proxy Socks 5" },
                { "ControlDeviceMenuDropBox5", "🗑️ Xóa" },
                { "ControlDeviceMenuDropBox6", "📱 Cài đặt ứng dụng" },
                { "LableViewDevice1", "Độ phân giải (sắc nét)" },
                { "LableViewDevice2", "Tỉ lệ khung hình(%)" },
                { "ControlCheckScreen", "Tắt màn hình khi xem" },
                { "LabelNumberDevice", "Số thiết bị được chọn" },
                { "Setting", "Cài đặt" },
                { "Document", "Hướng dẫn" },
                { "LogInfomation", "Thông tin" },
                { "LogError", "Lỗi" },
                { "LogWarning", "Cảnh báo" },
                { "logTitleProxy", "Bắt đầu fake proxy .." },
                { "logTitleProxySuccess", "Fake proxy thành công" },
                { "logCheckProxy", "Kiểm tra proxy trên web browserleaks" },
                { "logDeviceRandomEx", "Thiết bị không tồn tại, vui lòng thử lại" },
                { "logSelectDeviceChange", "Không có thiết bị được chọn" },
                { "logChangeDevice", "Bạn có chắc chắn muốn tiếp tục với những thay đổi này và khởi động lại không?" },
                { "logChangeDeviceKeyBox", "Bạn có muốn push file Keybox.xml vào điện thoại không?" },
                { "logChangeDevicePif", "Bạn có muốn push file Pif.json vào điện thoại không?" },
                { "logErrorExChangeDevice", "Thiết bị đã chọn này không thể thay đổi, vui lòng kiểm tra ROM và cài đặt nhà phát triển của bạn và thử tải lại." },
                { "logErrorExTitleChangeDevice", "Thiết bị lỗi" },
                { "TitleDetailDevice", "Thông tin thiết bị " },
                { "TitleProxy", "Nhập proxy cho thiết bị " },
                { "TitleProxyId", " có id " },
                { "TitleLocation", "Fake Location" },
                { "TitleUrl", "Nhập Url" },
                { "DeviceCount", "Thiết bị" },
                { "logPushFile", "Vui lòng chọn ít nhất một thiết bị để push file." },
                { "logPushFileSuccess", "Đã push file đến các thiết bị." },
                { "InfoSuccess", "Thành công" },
                { "logInstallAPK", "Vui lòng chọn ít nhất một thiết bị để cài APK." },
                { "logInstallAPKSuccess", "Đã cài APK cho các thiết bị." },
                { "logViewDevice", "Vui lòng chọn ít nhất 1 thiết bị để hiển thị scrcpy." },
                { "InfoViewDevice", "🔄 Đang hiển thị thiết bị" },
                { "logRunScript", "Chọn script run !" },
                { "logLoadScript", "Không có script tồn tại!" },
                { "logUntimateRunSctiptInfo", "Chạy script vĩnh viễn lần " },
                { "logRunSctiptInfo", "Chạy script lần " },
                { "logUntimateRunSctiptInfoSuccess", "Hoàn thành chạy vĩnh viễn " },
                { "logRunSctiptInfoSuccess", "Hoàn thành script" },
                { "DocumentFunction" , "Chức năng "},
                { "DocumentTitle" , "Hướng dẫn sự dụng tool "},
                { "DocumentTitleFunctionDevice" , "🤖 Chức năng thiết bị "},
                { "DocumentTitleFunctionAutomation" , "⚙️ Chức năng tự động hóa"},
                { "DocumentTitleFunctionScreen" , "📸 Chức năng xem màn hình"},
                { "DocumentFunctionMainDevice" , "• Các chức năng chính "},
                { "DocumentFunctionRandomDevice" , "Random device "},
                { "DocumentFunctionChangeDevice" , "Change device "},
                { "DocumentFunctionChangeSim" , "Change sim "},
                { "DocumentFunctionFakeProxy" , "Fake proxy "},
                { "DocumentFunctionFakeLocation" , "Fake location "},
                { "DocumentFunctionUpdateLocation" , "Update PlayIntegrityFix "},
                { "DocumentFunctionTitleRandomDevice" , "Chức năng random device: "},
                { "DocumentContentFunctionRandomDevice" , "cho phép bạn lấy ngẫu nhiên các thông tin nhận dạng thiết bị Android, giúp giả lập một thiết bị hoàn toàn mới. Đây là một tính năng quan trọng trong các tình huống cần thay đổi danh tính thiết bị để kiểm thử hoặc tránh bị nhận dạng trùng lặp "},
                { "DocumentFunctionTitleChangeDevice" , "Chức năng change device: "},
                { "DocumentContentFunctionChangeDevice" , "cho phép bạn thay đổi thông tin thiết bị Android theo một cấu hình cụ thể mà đã random từ trước hoặc chọn từ trước. "},
                { "DocumentFunctionTitleChangeSim","Chức năng change sim: " },
                { "DocumentContentFunctionChangeSim"," cho phép bạn thay đổi thông tin sim theo một cấu hình cụ thể mà đã random từ trước hoặc chọn từ trước. " },
                { "DocumentFunctionTitleFakeProxy" , "Chức năng fake proxy: "},
                { "DocumentContentFunctionFakeProxy1" , "cho phép bạn fake ip mặc định proxy đưa vào "},
                { "DocumentContentFunctionFakeProxy2" , "không có username và password vui lòng điền "},
                { "DocumentFunctionTitleFakeLocation" , "Chức năng fake location: "},
                { "DocumentContentFunctionFakeLocation" , "cho phép bạn giả lập vị trí cho trước"},
                { "DocumentAutomationTitleUIMain","• Giao diện chính "},
                { "DocumentAutomationTitleFunctionMain","Các chức năng chính "},
                { "DocumentAutomationTitleFunctionLoadFile","Load file script (load file) "},
                { "DocumentAutomationTitleFunctionRunScript","Chạy script (run script) "},
                { "DocumentAutomationTitleFunctionCodeScript","Cấu hình script (code script) "},
                { "DocumentAutomationTitleFunctionLoadDevice","Load device "},
                { "DocumentAutomationTitleFunctionBackup","Backup "},
                { "DocumentAutomationTitleFunctionScreenshot","Screenshot "},
                { "DocumentAutomationTitleFunctionRestore","Restore "},
                { "DocumentAutomationTitleFunctionDescription","Mô tả các chức năng "},
                { "DocumentAutomationTitleFunctionLoadFileContent","lấy file cấu hình script đã được thiết lập trước, được lưu cố định tại đường dẫn "},
                { "DocumentAutomationTitleFunctionRunScriptContent","lựa chọn số lượng lần chạy hoặc chọn chạy vĩnh viễn khi đó script được chọn sẽ được chạy auto trên các thiết bị, trong lúc script đang chạy bạn dừng, srcipt sẽ vẫn chạy đến khi hết hoàn thiện 1 lần của script. "},
                { "DocumentAutomationTitleFunctionLoadDeviceContent","hiện thị danh sách các thiết bị đang kết nối hoặc những thiết bị bị xóa khỏi danh sách. "},
                { "DocumentAutomationTitleFunctionBackupContent","đang phát triển... "},
                { "DocumentAutomationTitleFunctionScreenshotContent","chụp ảnh màn hình thiết bị, khi ở trạng thái chọn nhiều thiết bị nó có khả năng chụp cùng lúc. "},
                { "DocumentAutomationTitleFunctionRestoreContent","đang phát triển... "},
                { "DocumentAutomationTitleFunctionCodeScriptContent","giao diện khi sự dụng chức năng này ở hình 2, sự dụng các chức năng ở giao diện code script để tạo file script auto"},
                { "DocumentAutomationDetailHere","Chi tiết xem tại đây"},
                { "DocumentScreenTitleUIMain", "• Giao diện chính"},
                { "DocumentScreenTitleFunctionMain", "Các chức năng cơ bản"},
                { "DocumentScreenContent", "• Mô tả: là chức năng hiện thị các thiết bị kết nối, tự động view thiết bị có thể quan sát đa thiết bị một lúc tại giao diện này. Thiết bị khi được view sẽ được gán 1 số thứ tự dù thiết bị có mất kết nối và kết nối lại sau đó thiết bị vẫn giữ stt đó. Khung view sẽ hiện thị ip và country của ip"},
                { "DocumentScreenContentFunctionView", "View: chọn số lượng thiết bị để view( view này bạn có thể điều khiển được phone chứ k phải là chỉ xem như ở mặc định)"},
                { "DocumentScreenContentFunctionPushFile", "Push file : gửi file đến phone"},
                { "DocumentScreenContentFunctionInstallAPK", "Install apk: Cài apk cho phone"},
                { "DocumentScreenContentFunctionClickView", "Click vào Device - STT ở khung view mặc định bản sẽ mở chế độ điều khiển đơn thiết bị."},
                { "DocumentImageAutomationView","/Resources/Icons/automationview.jpg"},
                { "DocumentImageAutomationView1","/Resources/Icons/scriptAutomationview.jpg"},
                { "DocumentImageAutomationView2","/Resources/Icons/scriptAutomationview1.jpg"},
                { "DocumentImageAutomationView3","/Resources/Icons/scriptAutomationview2.jpg"},
                { "DocumentImageViewDevice","/Resources/Icons/viewdevice.jpg"},
                { "DocumentFunctionUpdatePlayIntegrityFixTitle1", "Chức năng Update IntegrityFix: "},
                { "DocumentFunctionUpdatePlayIntegrityFixTitle2", "là chức năng cho phép update keybox hoặc pif vào phone mà không bị thay đổi thông tin đã change từ đầu."},
                { "WebViewUrl","https://docs.google.com/document/d/1fqKkwLtDm9Hdi1fYw1Got3grV3KsWvAdKtamO0hqI74/preview"}
            }
        },
        {
          "en", new Dictionary<string, string>
            {
                { "Device", "Device" },
                { "Automation", "Automation" },
                { "Screen", "Screen" },
                { "langCheckBoxAutomation", "Unlimited" },
                { "ControlClickXY", "Click X, Y" },
                { "ControlSwipe", "Swipe" },
                { "ControlRandomClick", "Random Click" },
                { "ControlWait", "Wait" },
                { "TitleClickControl", "Click Coordinates" },
                { "TitleClick2Control", "Find Text Click" },
                { "ControlSearchAndClick", "Search and Click" },
                { "ControlSearchWaitClick", "Search and Wait" },
                { "ControlSearchAndContinue", "Search and Continue" },
                { "TitleClick3Control", "Find Text in Image" },
                { "ControlFindAndClick", "Find and Click" },
                { "ControlFindWaitClick", "Find and Wait" },
                { "ControlFindAndContinue", "Find and Continue" },
                { "TitleClick4Control", "Logic Processing" },
                { "TitleTextControl", "Text Processing" },
                { "ControlSendText", "Send Text" },
                { "ControlSendTextFromFileDel", "Send Text from File and Delete" },
                { "ControlSendTextRandomFromFile", "Send Text from Source" },
                { "ControlRandomTextAndSend", "Send Random Text" },
                { "ControlDelTextChar", "Delete One Character" },
                { "ControlDelAllText", "Delete All" },
                { "ControlSendKey", "Press Key" },
                { "ControlCtrlA", "Ctrl + A" },
                { "ControlCheckKeyBoard", "Check Keyboard" },
                { "ControlURLKEYSendText", "Key List" },
                { "TitileDataChangeInfo", "Phone Action Processing" },
                { "ControlDataChangeInfo1", "Backup" },
                { "ControlDataChangeInfo2", "Restore" },
                { "ControlDataChangeInfo3", "Login to Gmail" },
                { "ControlDataChangeInfo4", "Open Play Store" },
                { "ControlDataChangeInfo5", "Change Information" },
                { "ControlDataChangeInfo6", "Change SIM" },
                { "ControlDataChangeInfo7", "Delete Account" },
                { "ControlWaitReboot", "Wait for Reboot" },
                { "ControlWaitInternet", "Wait for Internet" },
                { "ControlPushFile", "Push File to Phone" },
                { "ControlPullFile", "Pull File to PC" },
                { "TitleGeneral", "Application Package" },
                { "ControlWiFiON", "Turn WiFi On" },
                { "ControlWiFiOFF", "Turn WiFi Off" },
                { "ControlOpenURL", "Open URL" },
                { "ControlRunCommandShell", "Shell Command" },
                { "ControlOpenApp", "Open App" },
                { "ControlCloseApp", "Close App" },
                { "ControlEnableApp", "Enable App" },
                { "ControlDisbledApp", "Disable App" },
                { "ControlInstallApp", "Install App" },
                { "ControlUninstallApp", "Uninstall App" },
                { "ControlClearDataApp", "Clear Data" },
                { "ControlSwipeCloseApp", "Swipe to Close App" },
                { "ControlLoadApp", "Load App" },
                { "ControlDeviceMenuDropBox1", "📋 Copy ID" },
                { "ControlDeviceMenuDropBox2", "ℹ️ Device Details" },
                { "ControlDeviceMenuDropBox3", "📱 View Devices" },
                { "ControlDeviceMenuDropBox4", "🌐 Fake Proxy HTTP" },
                { "ControlDeviceMenuDropBox4_1", "🌐 Fake Proxy Socks 5" },
                { "ControlDeviceMenuDropBox6", "📱 Install Apk" },
                { "ControlDeviceMenuDropBox5", "🗑️ Delete" },
                { "LableViewDevice1", "Resolution (Sharpness)" },
                { "LableViewDevice2", "Frame Rate (%)" },
                { "ControlCheckScreen", "Turn Off Screen While Viewing" },
                { "LabelNumberDevice", "Number of Selected Devices" },
                { "Setting", "Settings" },
                { "Document", "Documents" },
                { "LogInfomation", "Information" },
                { "LogError", "Error" },
                { "LogWarning", "Warning" },
                { "logTitleProxy", "Starting proxy spoofing..." },
                { "logTitleProxySuccess", "Proxy spoofing successful" },
                { "logCheckProxy", "Checking proxy on browserleaks website" },
                { "logDeviceRandomEx", "Device does not exist, please try again" },
                { "logSelectDeviceChange", "No device selected" },
                { "logChangeDevice", "Are you sure you want to proceed with these changes and restart?" },
                { "logChangeDeviceKeyBox", "Do you want to push the Keybox.xml file to the phone?" },
                { "logChangeDevicePif", "Do you want to push the Pif.json file to the phone?" },
                { "logErrorExChangeDevice", "The selected device cannot be changed. Please check your ROM and developer settings, then try reloading." },
                { "logErrorExTitleChangeDevice", "Device Error" },
                { "TitleDetailDevice", "Device Information" },
                { "TitleProxy", "Enter proxy for device" },
                { "TitleProxyId", " with ID " },
                { "TitleLocation", "Fake Location" },
                { "TitleUrl", "Enter URL" },
                { "DeviceCount", "Devices" },
                { "logPushFile", "Please select at least one device to push the file." },
                { "logPushFileSuccess", "File has been pushed to the devices." },
                { "InfoSuccess", "Success" },
                { "logInstallAPK", "Please select at least one device to install the APK." },
                { "logInstallAPKSuccess", "APK has been installed on the devices." },
                { "logViewDevice", "Please select at least one device to display with scrcpy." },
                { "InfoViewDevice", "🔄 Displaying device" },
                { "logRunScript", "Please select a script to run!" },
                { "logLoadScript", "No existing script found!" },
                { "logUntimateRunSctiptInfo", "Running script infinitely, iteration " },
                { "logRunSctiptInfo", "Running script, iteration " },
                { "logUntimateRunSctiptInfoSuccess", "Finished running infinite script" },
                { "logRunSctiptInfoSuccess", "Script completed" },
                { "DocumentFunction" , "Function" },
                { "DocumentTitle" , "Tool usage guide" },
                { "DocumentTitleFunctionDevice" , "🤖 Device functions" },
                { "DocumentTitleFunctionAutomation" , "⚙️ Automation functions" },
                { "DocumentTitleFunctionScreen" , "📸 Screen view functions" },
                { "DocumentFunctionMainDevice" , "• Main functions" },
                { "DocumentFunctionRandomDevice" , "Random device" },
                { "DocumentFunctionChangeDevice" , "Change device" },
                { "DocumentFunctionChangeSim" , "Change SIM" },
                { "DocumentFunctionFakeProxy" , "Fake proxy" },
                { "DocumentFunctionFakeLocation" , "Fake location" },
                { "DocumentFunctionUpdateLocation" , "Update PlayIntegrityFix" },
                { "DocumentFunctionTitleRandomDevice" , "Random device function:" },
                { "DocumentContentFunctionRandomDevice" , "Allows you to randomly generate Android device identification information, simulating a completely new device. This is important in situations requiring identity changes for testing or avoiding duplicate recognition." },
                { "DocumentFunctionTitleChangeDevice" , "Change device function:" },
                { "DocumentContentFunctionChangeDevice" , "Allows you to change the Android device information to a specific configuration that was previously randomized or selected." },
                { "DocumentFunctionTitleChangeSim","Change SIM function:" },
                { "DocumentContentFunctionChangeSim","Allows you to change SIM information based on a pre-randomized or selected configuration." },
                { "DocumentFunctionTitleFakeProxy" , "Fake proxy function:" },
                { "DocumentContentFunctionFakeProxy1" , "Allows you to fake an IP using the default proxy format " },
                { "DocumentContentFunctionFakeProxy2" , "If there is no username and password, please enter it as " },
                { "DocumentFunctionTitleFakeLocation" , "Fake location function:" },
                { "DocumentContentFunctionFakeLocation" , "Allows you to simulate a predefined location" },
                { "DocumentAutomationTitleUIMain", "• Main Interface" },
                { "DocumentAutomationTitleFunctionMain", "Main Functions" },
                { "DocumentAutomationTitleFunctionLoadFile", "Load Script File (load file)" },
                { "DocumentAutomationTitleFunctionRunScript", "Run Script" },
                { "DocumentAutomationTitleFunctionCodeScript", "Configure Script (code script)" },
                { "DocumentAutomationTitleFunctionLoadDevice", "Load Device" },
                { "DocumentAutomationTitleFunctionBackup", "Backup" },
                { "DocumentAutomationTitleFunctionScreenshot", "Screenshot" },
                { "DocumentAutomationTitleFunctionRestore", "Restore" },
                { "DocumentAutomationTitleFunctionDescription", "Function Descriptions" },
                { "DocumentAutomationTitleFunctionLoadFileContent", "Load a preconfigured script file, saved at the fixed path" },
                { "DocumentAutomationTitleFunctionRunScriptContent", "Choose the number of times to run or select to run indefinitely. The selected script will run automatically on the devices. If you stop it while running, the script will continue until it completes one full cycle." },
                { "DocumentAutomationTitleFunctionLoadDeviceContent", "Display the list of currently connected devices or those removed from the list." },
                { "DocumentAutomationTitleFunctionBackupContent", "Under development..." },
                { "DocumentAutomationTitleFunctionScreenshotContent", "Capture the device's screen. In multi-device mode, it can capture all selected devices simultaneously." },
                { "DocumentAutomationTitleFunctionRestoreContent", "Under development..." },
                { "DocumentAutomationTitleFunctionCodeScriptContent", "This interface corresponds to image 2. Use the functions in the code script interface to create an automatic script file." },
                { "DocumentAutomationDetailHere", "See details here" },
                { "DocumentScreenTitleUIMain", "• Main Interface" },
                { "DocumentScreenTitleFunctionMain", "Basic Functions" },
                { "DocumentScreenContent", "• Description: This feature displays connected devices, automatically showing them in the interface and allowing you to monitor multiple devices at once. Each viewed device is assigned an index number (STT). Even if a device disconnects and reconnects, it retains the same index. The view frame also shows the IP and country of the IP." },
                { "DocumentScreenContentFunctionView", "View: Select the number of devices to display (you can control the phones through this view, not just watch them like in the default mode)." },
                { "DocumentScreenContentFunctionPushFile", "Push file: Send a file to the phone." },
                { "DocumentScreenContentFunctionInstallAPK", "Install APK: Install an APK file on the phone." },
                { "DocumentScreenContentFunctionClickView", "Click on Device - STT in the default view frame to open single-device control mode." },
                { "DocumentImageAutomationView","/Resources/Icons/automationview.jpg"},
                { "DocumentImageAutomationView1","/Resources/Icons/ENscriptAutomationview.jpg"},
                { "DocumentImageAutomationView2","/Resources/Icons/ENscriptAutomationview1.jpg"},
                { "DocumentImageAutomationView3","/Resources/Icons/ENscriptAutomationview2.jpg"},
                { "DocumentImageViewDevice","/Resources/Icons/ENviewdevice.jpg"},
                { "DocumentFunctionUpdatePlayIntegrityFixTitle1", "Update IntegrityFix Function: "},
                { "DocumentFunctionUpdatePlayIntegrityFixTitle2", "this function allows updating the keybox or PIF on the phone without altering the information that was modified from the beginning."},
                { "WebViewUrl","https://docs.google.com/document/d/1UwrQ-j9-GBHLSnct0mJoZ5I4mBhcvHwN5Xe9ejSnjUc/preview"}
            }
        }
    };

        public static void SetLanguage(string language)
        {
            DeepDroid.Properties.Settings.Default.lang = language;
            DeepDroid.Properties.Settings.Default.Save();

            if (_translations.ContainsKey(language))
                _currentLanguage = language;
        }

        public static string Get(string key)
        {
            if (_translations.TryGetValue(_currentLanguage, out var langDict)
                && langDict.TryGetValue(key, out var value))
            {
                return value;
            }

            return key;
        }
    }
}
