//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ToolChange.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ToolChange.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] adb {
            get {
                object obj = ResourceManager.GetObject("adb", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] AdbWinApi {
            get {
                object obj = ResourceManager.GetObject("AdbWinApi", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] AdbWinUsbApi {
            get {
                object obj = ResourceManager.GetObject("AdbWinUsbApi", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] avcodec_61 {
            get {
                object obj = ResourceManager.GetObject("avcodec-61", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] avformat_61 {
            get {
                object obj = ResourceManager.GetObject("avformat-61", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] avutil_59 {
            get {
                object obj = ResourceManager.GetObject("avutil-59", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] carriers {
            get {
                object obj = ResourceManager.GetObject("carriers", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] checkPython {
            get {
                object obj = ResourceManager.GetObject("checkPython", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] curl {
            get {
                object obj = ResourceManager.GetObject("curl", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap icon {
            get {
                object obj = ResourceManager.GetObject("icon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] init_lineage16 {
            get {
                object obj = ResourceManager.GetObject("init.lineage16", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] init_lineage18 {
            get {
                object obj = ResourceManager.GetObject("init.lineage18", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] init_lineage20 {
            get {
                object obj = ResourceManager.GetObject("init.lineage20", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] iptables {
            get {
                object obj = ResourceManager.GetObject("iptables", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] libusb_1_0 {
            get {
                object obj = ResourceManager.GetObject("libusb-1.0", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Robinson
        ///Simmons
        ///Potter
        ///Jimenez
        ///Molina
        ///Lynn
        ///Ryan
        ///Branch
        ///Hunter
        ///Booker
        ///Russo
        ///Dougherty
        ///Goodwin
        ///Sexton
        ///Lin
        ///Benjamin
        ///Huber
        ///Garcia
        ///Richardson
        ///Mckay
        ///Hines
        ///Rose
        ///Stark
        ///Wright
        ///Harper
        ///Keller
        ///Michael
        ///Campbell
        ///Li
        ///Hooper
        ///Spears
        ///Griffith
        ///Irwin
        ///Mendez
        ///Ayers
        ///Park
        ///Holder
        ///Knapp
        ///Wiggins
        ///Mcfarland
        ///Cross
        ///Mueller
        ///Merritt
        ///Cooley
        ///Wong
        ///Sherman
        ///Jacobs
        ///Weiss
        ///Barber
        ///Camacho
        ///Campos
        ///Fernandez
        ///Lara
        ///Morrow
        ///Weaver
        ///Baxter
        ///Welch
        ///Maddox
        ///Beasley
        ///Herman
        ///Duncan
        ///Wall
        ///Castaneda
        ///Henry        /// [rest of string was truncated]&quot;;.
        /// </summary>
        public static string names {
            get {
                return ResourceManager.GetString("names", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] open_a_terminal_here {
            get {
                object obj = ResourceManager.GetObject("open_a_terminal_here", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] python {
            get {
                object obj = ResourceManager.GetObject("python", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] redsocks {
            get {
                object obj = ResourceManager.GetObject("redsocks", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] redsocks2 {
            get {
                object obj = ResourceManager.GetObject("redsocks2", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] scrcpy {
            get {
                object obj = ResourceManager.GetObject("scrcpy", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] scrcpy_console {
            get {
                object obj = ResourceManager.GetObject("scrcpy-console", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] scrcpy_noconsole {
            get {
                object obj = ResourceManager.GetObject("scrcpy-noconsole", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] scrcpy_server {
            get {
                object obj = ResourceManager.GetObject("scrcpy-server", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] SDL2 {
            get {
                object obj = ResourceManager.GetObject("SDL2", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] swresample_5 {
            get {
                object obj = ResourceManager.GetObject("swresample-5", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] tun2socks {
            get {
                object obj = ResourceManager.GetObject("tun2socks", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 97.0.4692.98_469209803
        ///96.0.4664.104_466410403
        ///95.0.4638.50_463805003
        ///94.0.4606.71_460607103
        ///93.0.4577.82_457708203
        ///92.0.4515.159_451515903
        ///91.0.4472.164_447216403.
        /// </summary>
        public static string webview {
            get {
                return ResourceManager.GetString("webview", resourceCulture);
            }
        }
    }
}
